_id: 5f78bd20-3384-11eb-bb5b-e3473ec65951
comment: >-
  Excellent post! I was wondering your thoughts regarding Hugo vs Jekyll. Also,
  is disqus and similar comment tools possible?
name: Gahis
date: '2020-12-01T03:21:59.685Z'
